#!/bin/bash
docker pull coral555/final-python-app:latest
docker stop python_server || true
docker rm python_server || true
docker run -d -p 5000:5000 --name python_server coral555/final-python-app:latest
